version: "3"
services:
  vue-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true